name: three_js
description: "Flutter package converted from threejs and three_dart to allow users to view, edit, and control 3D models."
version: 0.1.8
homepage: https://github.com/Knightro63/three_js/tree/main/packages/three_js

topics:
  - threejs
  - games
  - animations
  - flutter3d
  - model3d

environment:
  sdk: '>=3.3.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  three_js_math:
    path: ../three_js_math/
    version: any
  three_js_advanced_loaders:
    path: ../three_js_advanced_loaders/
    version: any
  three_js_animations:
    path: ../three_js_animations/
    version: any
  three_js_controls:
    path: ../three_js_controls/
    version: any
  three_js_core:
    path: ../three_js_core/
    version: any
  three_js_core_loaders:
    path: ../three_js_core_loaders/
    version: any
  three_js_curves:
    path: ../three_js_curves/
    version: any
  three_js_simple_loaders:
    path: ../three_js_simple_loaders/
    version: any
  three_js_text:
    path: ../three_js_text/
    version: any
  three_js_audio:
    path: ../three_js_audio/
    version: any
  three_js_geometry:
    path: ../three_js_geometry/
    version: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

platforms:
  android:
  ios:
  macos:
  web:
  windows: